version: '3.8'

services:
  postgres:
    build: .
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: abdo
      POSTGRES_PASSWORD: abdo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
